I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/anna.rpy", line 317, in script
    if D >= 14:
  File "game/anna.rpy", line 317, in <module>
    if D >= 14:
NameError: name 'D' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/anna.rpy", line 317, in script
    if D >= 14:
  File "C:\Users\Kim\Documents\renpy-8.1.3-sdk\renpy\ast.py", line 2133, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\Kim\Documents\renpy-8.1.3-sdk\renpy\python.py", line 1153, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Kim\Documents\renpy-8.1.3-sdk\renpy\python.py", line 1146, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/anna.rpy", line 317, in <module>
    if D >= 14:
NameError: name 'D' is not defined

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
Call It Fate 1.0
Sat Jan 13 05:05:21 2024
